// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqjvoyarqlujoiyfomep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xanZveWFycWx1am9peWZvbWVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MzI1NTIsImV4cCI6MjA2OTMwODU1Mn0.72GoMBn2eark9jnqTEdycNcf_7F9uYa7TZdA0EKf9yw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});